In [29]:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

1. How many negative numbers are there?

In [11]:
neg = (a < 0)
len(a[neg])

4

2. How many positive numbers are there?

In [10]:
pos = (a >= 0)
len(a[pos])

8

3. How many even positive numbers are there?



In [9]:
even_pos = (a >=0)&(a%2==0)
len(a[even_pos])

6

4. If you were to add 3 to each data point, how many positive numbers would there be?



In [17]:
add_three = a + 3
positive = (add_three >= 0)
len(add_three[positive])

10

5. If you squared each number, what would the new mean and standard deviation be?



In [30]:
mask_square = a ** 2
print(mask_square.mean())
print(mask_square.std())

74.0
144.0243035046516


6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.



In [35]:
print(a)
print(a.mean())
centered = a - 3
print(centered)
centered.mean()

[ 4 10 12 23 -2 -1  0  0  0 -6  3 -7]
3.0
[  1   7   9  20  -5  -4  -3  -3  -3  -9   0 -10]


0.0

7. Calculate the z-score for each data point. Recall that the z-score is given by:



In [38]:
import scipy.stats as stats
stats.zscore(a)

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [55]:
import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

* Use python's built in functionality/operators to determine the following:
* Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [57]:
sum_of_a = sum(a)
sum_of_a

55

* Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list


In [58]:
min_of_a = min(a)
min_of_a

1

* Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list


In [59]:
max_of_a = max(a)
max_of_a

10

* Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list


In [68]:
def average(a):
    return sum(a) / len(a)
mean_of_a = average(a)
mean_of_a

5.5

* Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together


In [69]:
def product(a):
    result = 1
    for x in a:
        result = result * x
    return result
product_of_a = product(a)
product_of_a

3628800

* Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]


In [70]:
def squared(a):
    squares = []
    for x in a:
        squares.append(x**2)
    return squares
squares_of_a = squared(a)
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

* Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers


In [72]:
def odds(a):
    odd_list = []
    for x in a:
        if x % 2 == 1:
            odd_list.append(x)
    return odd_list
odds_in_a = odds(a)
odds_in_a

[1, 3, 5, 7, 9]

* Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.


In [73]:
def evens(a):
    even_list = []
    for x in a:
        if x % 2 == 0:
            even_list.append(x)
    return even_list
evens_in_a = evens(a)
evens_in_a

[2, 4, 6, 8, 10]

In [74]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

* Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. Hint, you'll first need to make sure that the "b" variable is a numpy array


In [77]:
b_array = np.array(b)
sum_of_b = np.sum(b_array)
sum_of_b

33

* Exercise 2 - refactor the following to use numpy. 


In [80]:
min_of_b = np.min(b_array) 
min_of_b

3

* Exercise 3 - refactor the following maximum calculation to find the answer with numpy.


In [81]:
max_of_b = np.max(b_array)
max_of_b

8

* Exercise 4 - refactor the following using numpy to find the mean of b


In [82]:
mean_of_b = np.mean(b_array)
mean_of_b

5.5

* Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.


In [83]:
product_of_b = np.prod(b_array)
product_of_b

20160

* Exercise 6 - refactor the following to use numpy to find the list of squares 


In [86]:
squares_of_b = np.square(b_array)
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

* Exercise 7 - refactor using numpy to determine the odds_in_b


In [87]:
odds_in_b = b_array % 2 == 1
b_array[odds_in_b]

array([3, 5, 7])

* Exercise 8 - refactor the following to use numpy to filter only the even numbers


In [88]:
evens_in_b = b_array % 2 == 0
b_array[evens_in_b]

array([4, 6, 8])

* Exercise 9 - print out the shape of the array b.


In [90]:
b_array.shape

(2, 3)

* Exercise 10 - transpose the array b.


In [91]:
b_array.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

* Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)


In [93]:
b_array.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

* Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)


In [94]:
b_array.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [95]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

* HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
* Exercise 1 - Find the min, max, sum, and product of c.

In [100]:
c_array = np.array(c)
print(np.min(c_array))
print(np.max(c_array))
print(np.sum(c_array))
print(np.prod(c_array))

1
9
45
362880


* Exercise 2 - Determine the standard deviation of c.


In [101]:
np.std(c_array)

2.581988897471611

* Exercise 3 - Determine the variance of c.


In [102]:
np.var(c_array)

6.666666666666667

* Exercise 4 - Print out the shape of the array c


In [103]:
np.shape(c_array)

(3, 3)

* Exercise 5 - Transpose c and print out transposed result.


In [107]:
transpose = np.transpose(c_array)
transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

* Exercise 6 - Get the dot product of the array c with c. 


In [105]:
np.dot(c_array, c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

* Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261


In [110]:
np.sum(c * transpose)

261

* Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.


In [111]:
np.prod(c * transpose)

131681894400

In [112]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

* Exercise 1 - Find the sine of all the numbers in d


In [115]:
d_array = np.array(d)
np.sin(d_array)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

* Exercise 2 - Find the cosine of all the numbers in d


In [117]:
np.cos(d_array)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

* Exercise 3 - Find the tangent of all the numbers in d


In [119]:
np.tan(d_array)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

* Exercise 4 - Find all the negative numbers in d


In [122]:
negative_nums = d_array < 0
d_array[negative_nums]

array([-90, -30, -45, -45])

* Exercise 5 - Find all the positive numbers in d


In [123]:
positive_nums = d_array >= 0
d_array[positive_nums]

array([ 90,  30,  45,   0, 120, 180,  45, 270,  90,   0,  60,  45,  90,
       180])

* Exercise 6 - Return an array of only the unique numbers in d.


In [124]:
np.unique(d_array)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

* Exercise 7 - Determine how many unique numbers there are in d.


In [125]:
len(np.unique(d_array))

11

* Exercise 8 - Print out the shape of d.


In [126]:
np.shape(d_array)

(3, 6)

* Exercise 9 - Transpose and then print out the shape of d.


In [127]:
np.transpose(d_array)

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

* Exercise 10 - Reshape d into an array of 9 x 2


In [129]:
d_array.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])